# Your first tensorflow program (SHIFT + ENTER TO EXEC a BLOCK)

In [2]:
import tensorflow as tf #import tensorflow library

# Build a graph.
a = tf.constant(5.0) 
b = tf.constant(6.0) 
c=a*b
# Launch the graph in a session.
sess = tf.Session()
# Evaluate the tensor `c`.
print(sess.run(c))
#print(c)
sess.close()

30.0


## Initiate a session: Tf.session()

In [3]:
import tensorflow as tf #import tensorflow library
# Build a graph.
a = 5 #tf.constant(5.0) 
b = tf.constant(6.0) 
c=a*b
# Launch the graph in a session.
with tf.Session() as sess: 
    # Evaluate the tensor `c`.
    print(sess.run(c))
    
# sess will be closed automatically after "with block"

30.0


## Feeding the execution graph
A graph can be parameterized to accept external inputs  
A placeholder is a promise to provide a value later, like a function argument

In [6]:
x = tf.placeholder(tf.float32) 
y = tf.placeholder(tf.float32) 
z=x+y
with tf.Session() as sess:
    print(sess.run(z, feed_dict={x: 3, y: 4.5}))
    print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))
    print(sess.run(z, feed_dict={x: 30, y: 4.5}))

7.5
[3. 7.]
34.5


## tf.InteractiveSession  
an InteractiveSession installs itself as the default session on construction. The methods tf.Tensor.eval and tf.Operation.runwill use that session to run ops.


In [7]:
sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
# We can just use 'c.eval()' without passing 'sess'
print(c.eval())    
print(sess.run(c))
sess.close()

30.0


## Subgraphs
Session does not evaluate every tensors in the graph

In [10]:
import tensorflow as tf
x = tf.constant(2, name='x')
y = tf.constant(3, name='y')
z = tf.constant(4, name='z')
x_y = tf.add(x, y, name='x_y')
y_z = tf.add(y, z, name='y_z')
x_y_z = tf.add(x, y_z, name='x_y_z')
x_y_y_z = tf.add(x_y, y_z, name='x_y_y_z')
writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(x_y_y_z))
    print(x_y_z)


12
Tensor("x_y_z_2:0", shape=(), dtype=int32)


# tf operations

## tf.rank

In [14]:
mammal = tf.Variable("Elephant", tf.string) 
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.14159265359, tf.float64)
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers = tf.Variable([3.14159, 2.71828], tf.float32) 
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False, True],[True, False]], tf.bool) 
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32) 
#squarish_squares = tf.Variable([ [4, 9, 0], [16, 25, 12] ], tf.int32)
squarish_squares = tf.Variable([ [4, 9, 0]], tf.int32)

In [6]:
print(tf.rank(mammal))

Tensor("Rank:0", shape=(), dtype=int32)


Please use tf.rank(your_tensor) to know ranks of all above tensors?

In [15]:
with tf.Session() as sess:
    print("cool numbers", sess.run(tf.rank(cool_numbers)))
    print("ignition", sess.run(tf.rank(ignition)))
    print("squarish_squares", sess.run(tf.rank(squarish_squares)))
    print("first_primes", sess.run(tf.rank(first_primes)))
    print("cool numbers", sess.run(tf.shape(squarish_squares)))

cool numbers 1
ignition 0
squarish_squares 2
first_primes 1
cool numbers [1 3]


## Tensor slices

In [33]:
my_matrix = tf.constant([[[1,2,3],[3,5,6], [7,8,9], [10,11,12]]])
my_row_vector = my_matrix[0]
# shape mymatrix [1, 4, 3]
my_column_vector = my_matrix[0, 1, 1]
# shape = [1, 4]
with tf.Session() as sess:
    x, y, z = sess.run([my_matrix, my_row_vector, my_column_vector])
    #x, y = sess.run([my_matrix, my_row_vector])
    #print('x=', x)
    #print('y=', y)
    #print('z=', z)
    #print(sess.run([tf.shape(my_matrix)]))
    print(sess.run(tf.shape(my_matrix)))
    print(y)
    print(x)
    print(z)
    print(sess.run(tf.shape(my_column_vector)))

[1 4 3]
[[ 1  2  3]
 [ 3  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 3  5  6]
  [ 7  8  9]
  [10 11 12]]]
5
[]


In [53]:
my_matrix = tf.Variable([1,2,3,4,5,6,7,8,9], tf.int32)
my_new_matrix = tf.reshape(my_matrix, [1,3,3])
my_new_matrix_2 = tf.reshape(my_matrix, [3,1,3])
my_new_matrix_3 = tf.reshape(my_matrix, [3,3,1])
with tf.Session() as sess:
    #print(sess.run(my_matrix, feed_dict={my_matrix:[1,2,2,2,2,2,2,2,2]}))
    sess.run(tf.global_variables_initializer())
    print(sess.run(my_matrix))
    #print(sess.run(my_new_matrix))
    #print(sess.run(my_new_matrix_2))
    #print(sess.run(my_new_matrix_3))
    #print(sess.run(tf.reshape(my_new_matrix_3,[9])))

[1 2 3 4 5 6 7 8 9]


## tf.cond(pred, fn1, fn2, name=None)
Return either fn1() or fn2() based on the boolean predicate pred.
fn1 and fn2 both return lists of output tensors. fn1 and fn2 must have the same non-zero number and type of outputs.

In [ ]:
import tensorflow as tf #import tensorflow library
a = 10
b = 2
x = tf.Variable(5)
y = tf.Variable(30)
z = tf.multiply(a, b)
result = tf.cond(x < y, lambda: tf.add(x, z), lambda: tf.square(y))
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(result.eval())

In [35]:
rank_three_tensor = tf.ones([2, 3])
matrix = tf.reshape(rank_three_tensor, [6])

In [36]:
with tf.Session() as sess:
    print(sess.run(rank_three_tensor))
    print(sess.run(matrix))

[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1. 1.]


In [51]:
# Initialize session in interactive mode
import tensorflow as tf
#sess = tf.InteractiveSession()

# Some tensor we want to print the value of
a = tf.constant([1.0, 3.0])

# Add print operation
#a = tf.Print(a, [a], message="This is a: ")
#tf.Print(a, [a], message="This is a: ")
#a = tf.print(a, [a], message="This is a: ")

# Add more elements of the graph using a
b = tf.add(a, a)
with tf.Session() as sess:
    print(b.eval())


[2. 6.]


In [39]:
sess.close()

In [45]:
tmp = tf.zeros([3,4,5], dtype=tf.float32, name=None)
one = tf.ones_like(tmp, dtype=tf.float32)

In [46]:
with tf.Session() as sess:
    print(sess.run(tmp))
    print(sess.run(one))

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [50]:
my_const = tf.constant([1, 2, 3, 4, 5])
with tf.Session() as sess:
    print(sess.graph.as_graph_def())

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 5.0
      }
    }
  }
}
node {
  name: "Const_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 6.0
      }
    }
  }
}
node {
  name: "mul"
  op: "Mul"
  input: "Const"
  input: "Const_1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "Const_2"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 5.0
      }
    }
  }
}
node {
  name: "Const_3"
  op: "Const"
  attr {
    key: "dtype"
    value {
      

In [51]:
s = tf.Variable(2, name="scalar")
m = tf.Variable([[0, 1], [2, 3]], name="matrix")
W = tf.Variable(tf.zeros([784,10]))


In [54]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run([s, m, W]))

[2, array([[0, 1],
       [2, 3]], dtype=int32), array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)]


In [54]:
# define the graph 
x = tf.Variable(5)
x.assign(50)
# launch the session
with tf.Session() as sess:
    sess.run(x.initializer)
    print(x.eval())

5


In [56]:
x = tf.Variable(5)
op = x.assign(50)
with tf.Session() as sess:
    sess.run(x.initializer)
    sess.run(op)
    print(x.eval())

50


In [61]:
# Tf.Variable
number = tf.Variable(2)
multiplier = tf.Variable(1)
multiplier = multiplier.assign_add(1)
init = tf.global_variables_initializer()
result = tf.multiply(number,multiplier)
with tf.Session() as sess:
    sess.run(init)
    for i in range(10):
        x, y, z = sess.run([number, multiplier,result])
        print("Result number: {} * multiplier: {} = {}".format(x, y, z))


Result number: 2 * multiplier: 2 = 4
Result number: 2 * multiplier: 3 = 6
Result number: 2 * multiplier: 4 = 8
Result number: 2 * multiplier: 5 = 10
Result number: 2 * multiplier: 6 = 12
Result number: 2 * multiplier: 7 = 14
Result number: 2 * multiplier: 8 = 16
Result number: 2 * multiplier: 9 = 18
Result number: 2 * multiplier: 10 = 20
Result number: 2 * multiplier: 11 = 22


In [60]:
# Tf.constant
number = tf.constant(2)
multiplier = tf.constant(1)
multiplier = tf.add(multiplier, 1)
result = tf.multiply(number,multiplier)
with tf.Session() as sess:
    sess.run(init)
    for i in range(10):
        print("Result number * multiplier = ",sess.run(result))


Result number * multiplier =  4
Result number * multiplier =  4
Result number * multiplier =  4
Result number * multiplier =  4
Result number * multiplier =  4
Result number * multiplier =  4
Result number * multiplier =  4
Result number * multiplier =  4
Result number * multiplier =  4
Result number * multiplier =  4


In [71]:
import numpy as np
import tensorflow as tf
with tf.Graph().as_default() as g:
    x = tf.constant(2, tf.int32)
    y = x * x
    g.prevent_feeding(x)e
    g.prevent_feeding(y)

    with tf.Session() as sess:
        print(sess.run(y, feed_dict={x: 4}))
        print(sess.graph.is_feedable(y))

ValueError: Tensor Tensor("Const:0", shape=(), dtype=int32) may not be fed.